fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print(fruits)
# print(fruits.count('apple'))
# print(fruits.count('tangerine'))
# print(fruits.index('banana'))
# print(fruits.index('banana', 4))  # Find next banana starting a position 4
fruits.reverse()
print(fruits)
fruits.reverse()
print(fruits)
fruits.insert(0, 'dragonfruit')
print(fruits)
# print(fruits.append('grape'))
# print(fruits)
# print(fruits.sort())
# print(fruits)
# fruits.pop()
# print(fruits)
